--DROP TABLE teachers IF EXISTS;
--
--CREATE TABLE teachers (
--    id          INTEGER IDENTITY PRIMARY KEY,
--    first_name  VARCHAR(30),
--    last_name   VARCHAR(30)
--);
--
--CREATE TABLE bills (
--    id          INTEGER IDENTITY PRIMARY KEY,
--    first_name  VARCHAR(30),
--    last_name   VARCHAR(30)
--);
--
--CREATE TABLE classes (
--    id          INTEGER IDENTITY PRIMARY KEY,
--    first_name  VARCHAR(30),
--    last_name   VARCHAR(30)
--);
--
--CREATE TABLE departments (
--    id          INTEGER IDENTITY PRIMARY KEY,
--    first_name  VARCHAR(30),
--    last_name   VARCHAR(30)
--);
--
--CREATE TABLE grades (
--    id          INTEGER IDENTITY PRIMARY KEY,
--    first_name  VARCHAR(30),
--    last_name   VARCHAR(30)
--);
--
--CREATE TABLE salaries (
--    id          INTEGER IDENTITY PRIMARY KEY,
--    first_name  VARCHAR(30),
--    last_name   VARCHAR(30)
--);
--
--CREATE TABLE schools (
--    id          INTEGER IDENTITY PRIMARY KEY,
--    first_name  VARCHAR(30),
--    last_name   VARCHAR(30)
--);
--
--CREATE TABLE students (
--    id          INTEGER IDENTITY PRIMARY KEY,
--    first_name  VARCHAR(30),
--    last_name   VARCHAR(30)
--);
--
--CREATE TABLE subjects (
--    id          INTEGER IDENTITY PRIMARY KEY,
--    first_name  VARCHAR(30),
--    last_name   VARCHAR(30)
--);

