server:
  port: 8000

  spring:
    neo4j:
      uri: neo4j://localhost:7687
      authentication:
        username: neo4j
        password: secret

logging:
  level:
    org:
      springframework:
        data:
          neo4j: DEBUG

  spring:
    data:
      neo4j:
        database: my-database