# database init, supports mysql too
#database: 2
#spring:
#  datasource:
#    schema: classpath*:db/${database}/schema.sql
#    data: classpath*:db/${database}/data.sql

  # JPA
#  jpa:
#    hibernate:
#      ddl-auto: none
#    open-in-view: false

  # Maximum time static resources should be cached
#  resources:
#    cache:
#      cachecontrol:
#        max-age: 12h

  # Logging
logging:
  level:
    org:
      springframework: INFO

  # Actuator
management:
  endpoints:
    web:
      exposure:
        include: health